apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  namespace: enteral-kingdom
spec:
  type: ClusterIP   # ✅ Chuyển từ NodePort → ClusterIP
  selector:
    app: enteral-kingdom-landing-page
  ports:
  - protocol: TCP
    port: 80          # Port của Service (Ingress sẽ forward vào đây)
    targetPort: 80    # Port của container